### ISSUE TITLE
Add base_rul on client constructor

### ISSUE THREAD

**Issue by huberemanuel** [coder543/llm-speed-benchmark#1]
Hey, nice project!

I've used with vllm and it was missing one parameter on the client's constructor:

```py
    # Initialize the OpenAI client
    client = OpenAI(
	base_url=os.environ.get("OPENAI_BASE_URL"),
        api_key=os.environ.get("OPENAI_API_KEY")
    )
```

After this change, I was able to run the benchmark.

**Comment by coder543** [comment]
I haven’t tried it today, but I believe the default constructor already uses that environment variable if it is set. So, I’m not sure why that change would have helped, but I’m glad it helped your use case!
